### ISSUE TITLE
Xcode build failed, exit code 2

### ISSUE THREAD

**Issue by sabont** [AbePralle/PlasmacoreDemos#1]
I downloaded from latest followed instructions in readme opened the iOS project in Xcode and tried to build & run, but it is failing.

Showing Recent Issues
Compiling ImageCompiler...
ld: library not found for -lfreetype
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: **\* [Build/imagecompiler] Error 1
make: **\* [compile_images] Error 2
Command /bin/sh failed with exit code 2

<img width="1512" alt="screen shot 2016-10-24 at 9 36 29 pm" src="https://cloud.githubusercontent.com/assets/5597207/19673149/12b93932-9a32-11e6-8a68-2d97368bac1e.png">
![screen shot 2016-10-24 at 9 37 15 pm](https://cloud.githubusercontent.com/assets/5597207/19673150/12d3c0e0-9a32-11e6-9a4c-2014c4277355.png)
![screen shot 2016-10-24 at 9 42 26 pm](https://cloud.githubusercontent.com/assets/5597207/19673235/ca1bd30a-9a32-11e6-95cb-e470b40488a5.png)

**Comment by AbePralle** [comment]
I can't tell why it's failing to link that library.

The library is the precompiled file `SlidingPuzzle/Libraries/FreeType/libfreetype.a`.  If I rename that file then I get the same link error, but otherwise it's fine.  Double-check that the file exists and is 3562144 bytes.

Next try unsilencing line 130 of `Libraries/ImageCompiler/Makefile` (remove the `@` from `@clang++ ...`) and see if you get a compile command with the following elements:

```
clang++ ... -L../FreeType/Mac -lfreetype ...
```

If that looks good, try creating an empty `Test.cpp` file in the `ImageCompiler/` folder and then type:

```
g++ Test.cpp -lfreetype -L../FreeType/Mac
```

Does it give a "library not found" error or an "Undefined _main" error?

I have the exact same version of Xcode as you and macOS Sierra 10.12 (not 10.12.1 - no update is currently available for me).

**Comment by AbePralle** [comment]
Found it - `libfreetype.a` was missing from the repo.  Just `git pull` and it should work now!

There was a perfect storm of events.  When developing this demo I picked a GitHub `C++` filter without noticing that it automatically omits `.a` files.  I then developed the demo with the Plasmacore "Bootstrap" command, which copied the `.a` file in.  Finally, when taking a look tonight I first started in the actual Plasmacore repo, renamed the file, and confirmed that the project failed to compile _and_ that the `.a` was now considered missing from the repo.
